### ISSUE TITLE
PackageTransmute

### ISSUE THREAD

**Issue by andhherson** [wilsonfreitas/R-fixedincome#18]
Does this package still works? I'm having some problemns to install it

**Comment by wilsonfreitas** [comment]
Hi @andhherson, this project will be discontinued. By the way, this package doesn't use `transmute`.
`transmute` is `rbmfbovespa`'s dependency and also in this project this dependency will be replaced.

**Comment by andhherson** [comment]
Valeu!!

Em dom, 29 de abr de 2018 às 09:53, Wilson Freitas <notifications@github.com>
escreveu:
